[package]
name = "autd3-backend-cuda"
version = "22.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "CUDA Backend for AUTD3"
repository = "https://github.com/shinolab/autd3-backend-cuda"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { version = "22.0.0" }
autd3-gain-holo = { version = "22.0.0" }
cuda-sys = "0.2.0"
nalgebra = { version = "0.32.1", default-features = false, features = ["std"] }
rand = "0.8.5"
thiserror = "1.0.31"

[dev-dependencies]
anyhow = "1.0.75"
autd3 = "22.0.0"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
criterion = { version = "0.5.1", features = ["html_reports"] }

[build-dependencies]
cc = "1.0.79"
cuda-config = "0.1.0"

[features]
default = []
single_float = ["autd3-driver/single_float", "autd3-gain-holo/single_float"]
use_meter = ["autd3-driver/use_meter"]
test-utilities = ["autd3-gain-holo/test-utilities"]
bench-utilities = ["autd3-gain-holo/criterion"]
async-trait = ["autd3-driver/async-trait", "autd3-gain-holo/async-trait"]

[[bench]]
name = "holo"
path = "benches/holo.rs"
harness = false
