[package]
name = "autd3-backend-cuda"
version = "27.0.0-alpha.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "CUDA Backend for AUTD3"
repository = "https://github.com/shinolab/autd3-backend-cuda"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { version = "27.0.0-alpha.3" }
autd3-gain-holo = { version = "27.0.0-alpha.3" }
bit-vec = "0.8.0"
cuda-sys = "0.2.0"
nalgebra = { version = "0.33.0", default-features = false, features = ["std"] }
rand = "0.8.5"
thiserror = "1.0.63"

[dev-dependencies]
anyhow = "1.0.86"
autd3 = "27.0.0-alpha.2"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
criterion = { version = "0.5.1", features = ["html_reports"] }
rstest = "0.21.0"
assert_approx_eq = "1.1.0"
approx = "0.5.1"

[build-dependencies]
cc = "1.1.6"
cuda-config = "0.1.0"

[features]
default = []
bench-utilities = ["autd3-gain-holo/bench-utilities"]
async-trait = ["autd3-driver/async-trait", "autd3-gain-holo/async-trait"]
use_meter = []

[[bench]]
name = "holo"
path = "benches/holo.rs"
harness = false
