/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cusolverDnContext {
    _unused: [u8; 0],
}
pub type cusolverDnHandle_t = *mut cusolverDnContext;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cusolverDnParams {
    _unused: [u8; 0],
}
pub type cusolverDnParams_t = *mut cusolverDnParams;
pub const cudaDataType_t_CUDA_R_16F: cudaDataType_t = 2;
pub const cudaDataType_t_CUDA_C_16F: cudaDataType_t = 6;
pub const cudaDataType_t_CUDA_R_16BF: cudaDataType_t = 14;
pub const cudaDataType_t_CUDA_C_16BF: cudaDataType_t = 15;
pub const cudaDataType_t_CUDA_R_32F: cudaDataType_t = 0;
pub const cudaDataType_t_CUDA_C_32F: cudaDataType_t = 4;
pub const cudaDataType_t_CUDA_R_64F: cudaDataType_t = 1;
pub const cudaDataType_t_CUDA_C_64F: cudaDataType_t = 5;
pub const cudaDataType_t_CUDA_R_4I: cudaDataType_t = 16;
pub const cudaDataType_t_CUDA_C_4I: cudaDataType_t = 17;
pub const cudaDataType_t_CUDA_R_4U: cudaDataType_t = 18;
pub const cudaDataType_t_CUDA_C_4U: cudaDataType_t = 19;
pub const cudaDataType_t_CUDA_R_8I: cudaDataType_t = 3;
pub const cudaDataType_t_CUDA_C_8I: cudaDataType_t = 7;
pub const cudaDataType_t_CUDA_R_8U: cudaDataType_t = 8;
pub const cudaDataType_t_CUDA_C_8U: cudaDataType_t = 9;
pub const cudaDataType_t_CUDA_R_16I: cudaDataType_t = 20;
pub const cudaDataType_t_CUDA_C_16I: cudaDataType_t = 21;
pub const cudaDataType_t_CUDA_R_16U: cudaDataType_t = 22;
pub const cudaDataType_t_CUDA_C_16U: cudaDataType_t = 23;
pub const cudaDataType_t_CUDA_R_32I: cudaDataType_t = 10;
pub const cudaDataType_t_CUDA_C_32I: cudaDataType_t = 11;
pub const cudaDataType_t_CUDA_R_32U: cudaDataType_t = 12;
pub const cudaDataType_t_CUDA_C_32U: cudaDataType_t = 13;
pub const cudaDataType_t_CUDA_R_64I: cudaDataType_t = 24;
pub const cudaDataType_t_CUDA_C_64I: cudaDataType_t = 25;
pub const cudaDataType_t_CUDA_R_64U: cudaDataType_t = 26;
pub const cudaDataType_t_CUDA_C_64U: cudaDataType_t = 27;
pub const cudaDataType_t_CUDA_R_8F_E4M3: cudaDataType_t = 28;
pub const cudaDataType_t_CUDA_R_8F_UE4M3: cudaDataType_t = 28;
pub const cudaDataType_t_CUDA_R_8F_E5M2: cudaDataType_t = 29;
pub const cudaDataType_t_CUDA_R_8F_UE8M0: cudaDataType_t = 30;
pub const cudaDataType_t_CUDA_R_6F_E2M3: cudaDataType_t = 31;
pub const cudaDataType_t_CUDA_R_6F_E3M2: cudaDataType_t = 32;
pub const cudaDataType_t_CUDA_R_4F_E2M1: cudaDataType_t = 33;
pub type cudaDataType_t = ::std::os::raw::c_uint;
pub use self::cudaDataType_t as cudaDataType;
pub const cublasFillMode_t_CUBLAS_FILL_MODE_LOWER: cublasFillMode_t = 0;
pub const cublasFillMode_t_CUBLAS_FILL_MODE_UPPER: cublasFillMode_t = 1;
pub const cublasFillMode_t_CUBLAS_FILL_MODE_FULL: cublasFillMode_t = 2;
pub type cublasFillMode_t = ::std::os::raw::c_uint;
pub const cusolverStatus_t_CUSOLVER_STATUS_SUCCESS: cusolverStatus_t = 0;
pub const cusolverStatus_t_CUSOLVER_STATUS_NOT_INITIALIZED: cusolverStatus_t = 1;
pub const cusolverStatus_t_CUSOLVER_STATUS_ALLOC_FAILED: cusolverStatus_t = 2;
pub const cusolverStatus_t_CUSOLVER_STATUS_INVALID_VALUE: cusolverStatus_t = 3;
pub const cusolverStatus_t_CUSOLVER_STATUS_ARCH_MISMATCH: cusolverStatus_t = 4;
pub const cusolverStatus_t_CUSOLVER_STATUS_MAPPING_ERROR: cusolverStatus_t = 5;
pub const cusolverStatus_t_CUSOLVER_STATUS_EXECUTION_FAILED: cusolverStatus_t = 6;
pub const cusolverStatus_t_CUSOLVER_STATUS_INTERNAL_ERROR: cusolverStatus_t = 7;
pub const cusolverStatus_t_CUSOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED: cusolverStatus_t = 8;
pub const cusolverStatus_t_CUSOLVER_STATUS_NOT_SUPPORTED: cusolverStatus_t = 9;
pub const cusolverStatus_t_CUSOLVER_STATUS_ZERO_PIVOT: cusolverStatus_t = 10;
pub const cusolverStatus_t_CUSOLVER_STATUS_INVALID_LICENSE: cusolverStatus_t = 11;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_PARAMS_NOT_INITIALIZED: cusolverStatus_t = 12;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_PARAMS_INVALID: cusolverStatus_t = 13;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_PARAMS_INVALID_PREC: cusolverStatus_t = 14;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_PARAMS_INVALID_REFINE: cusolverStatus_t = 15;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_PARAMS_INVALID_MAXITER: cusolverStatus_t = 16;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_INTERNAL_ERROR: cusolverStatus_t = 20;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_NOT_SUPPORTED: cusolverStatus_t = 21;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_OUT_OF_RANGE: cusolverStatus_t = 22;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_NRHS_NOT_SUPPORTED_FOR_REFINE_GMRES:
    cusolverStatus_t = 23;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_INFOS_NOT_INITIALIZED: cusolverStatus_t = 25;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_INFOS_NOT_DESTROYED: cusolverStatus_t = 26;
pub const cusolverStatus_t_CUSOLVER_STATUS_IRS_MATRIX_SINGULAR: cusolverStatus_t = 30;
pub const cusolverStatus_t_CUSOLVER_STATUS_INVALID_WORKSPACE: cusolverStatus_t = 31;
pub type cusolverStatus_t = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn cusolverDnCreate(handle: *mut cusolverDnHandle_t) -> cusolverStatus_t;
}
unsafe extern "C" {
    pub fn cusolverDnDestroy(handle: cusolverDnHandle_t) -> cusolverStatus_t;
}
unsafe extern "C" {
    pub fn cusolverDnXpotrf_bufferSize(
        handle: cusolverDnHandle_t,
        params: cusolverDnParams_t,
        uplo: cublasFillMode_t,
        n: i64,
        dataTypeA: cudaDataType,
        A: *const ::std::os::raw::c_void,
        lda: i64,
        computeType: cudaDataType,
        workspaceInBytesOnDevice: *mut usize,
        workspaceInBytesOnHost: *mut usize,
    ) -> cusolverStatus_t;
}
unsafe extern "C" {
    pub fn cusolverDnXpotrf(
        handle: cusolverDnHandle_t,
        params: cusolverDnParams_t,
        uplo: cublasFillMode_t,
        n: i64,
        dataTypeA: cudaDataType,
        A: *mut ::std::os::raw::c_void,
        lda: i64,
        computeType: cudaDataType,
        bufferOnDevice: *mut ::std::os::raw::c_void,
        workspaceInBytesOnDevice: usize,
        bufferOnHost: *mut ::std::os::raw::c_void,
        workspaceInBytesOnHost: usize,
        info: *mut ::std::os::raw::c_int,
    ) -> cusolverStatus_t;
}
unsafe extern "C" {
    pub fn cusolverDnXpotrs(
        handle: cusolverDnHandle_t,
        params: cusolverDnParams_t,
        uplo: cublasFillMode_t,
        n: i64,
        nrhs: i64,
        dataTypeA: cudaDataType,
        A: *const ::std::os::raw::c_void,
        lda: i64,
        dataTypeB: cudaDataType,
        B: *mut ::std::os::raw::c_void,
        ldb: i64,
        info: *mut ::std::os::raw::c_int,
    ) -> cusolverStatus_t;
}
