name: build

on:
  pull_request: {}
  merge_group:
    branches: [ "main" ]

jobs:

  changed-files:
    name: changed-files
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            src:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/*.cu'

  test:
    needs: changed-files
    name: test-on-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        if: ${{ needs.changed-files.outputs.src == 'true' }}
      - uses: ./.github/actions/setup-build
        with:
          os: ${{ matrix.os }}
        if: ${{ needs.changed-files.outputs.src == 'true' }}
      - run: cargo build
        shell: bash
        if: ${{ needs.changed-files.outputs.src == 'true' }}

  lint:
    needs: changed-files
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ needs.changed-files.outputs.src == 'true' }}
      - uses: ./.github/actions/setup-build
        with:
          os: ubuntu-latest
        if: ${{ needs.changed-files.outputs.src == 'true' }}
      - run: cargo clippy -- -D warnings
        if: ${{ needs.changed-files.outputs.src == 'true' }}
